theme: jekyll-theme-slate
title: The homepage of Elvira Kinzhaeva, a master student from the school of International Media, Communication and Tourism studies
description: This website is my personal photo portfolio as a photographer and researcher.
plugins:
  - jemoji
url: "https://elvirakinzhaeva.github.io/"
markdown: kramdown
