theme: pages-themes/tactile@v0.2.0
title: The homepage of Elvira Kinzhaeva
description: A personal website of Elvira Kinzhaeva.
plugins:
- jekyll-remote-theme
- jemoji
url: "https://elvirakinzhaeva.github.io/"
markdown: kramdown
