theme: jekyll-theme-minimal
title: The homepage of Elvira Kinzhaeva
description: This website is my personal photo portfolio as a photographer and researcher.
plugins:
  - jemoji
url: "https://elvirakinzhaeva.github.io/"
markdown: kramdown
